// <auto-generated />
using System;
using Backend_jobby.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend_jobby.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005171200_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend_jobby.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("CvSnapshotJson")
                        .HasColumnType("text")
                        .HasColumnName("cv_snapshot_json");

                    b.Property<bool>("IsTailoredCv")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tailored_cv");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("JobseekerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobseeker_profile_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_applications_job_id");

                    b.HasIndex("JobseekerProfileId", "JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_applications_jobseeker_profile_id_job_id");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("ix_conversations_application_id");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.EmployerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyInitials")
                        .HasColumnType("text")
                        .HasColumnName("company_initials");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_employer_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_employer_profiles_user_id");

                    b.ToTable("employer_profiles", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.IgnoredJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("JobseekerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobseeker_profile_id");

                    b.Property<DateTime>("PassedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("passed_at");

                    b.HasKey("Id")
                        .HasName("pk_ignored_jobs");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_ignored_jobs_job_id");

                    b.HasIndex("JobseekerProfileId", "JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_ignored_jobs_jobseeker_profile_id_job_id");

                    b.ToTable("ignored_jobs", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyInitials")
                        .HasColumnType("text")
                        .HasColumnName("company_initials");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("distance_km");

                    b.Property<Guid?>("EmployerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("employer_profile_id");

                    b.Property<string>("FirstMessage")
                        .HasColumnType("text")
                        .HasColumnName("first_message");

                    b.Property<decimal>("HourlyPay")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("hourly_pay");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("PrimarySkill")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_skill");

                    b.Property<string>("StartDateText")
                        .HasColumnType("text")
                        .HasColumnName("start_date_text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("text")
                        .HasColumnName("working_hours");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("EmployerProfileId")
                        .HasDatabaseName("ix_jobs_employer_profile_id");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.JobAccommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccommodationCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accommodation_code");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.HasKey("Id")
                        .HasName("pk_job_accommodations");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_accommodations_job_id");

                    b.ToTable("job_accommodations", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.JobOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("OfferText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("offer_text");

                    b.HasKey("Id")
                        .HasName("pk_job_offers");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_offers_job_id");

                    b.ToTable("job_offers", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.JobRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("RequirementText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requirement_text");

                    b.HasKey("Id")
                        .HasName("pk_job_requirements");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_requirements_job_id");

                    b.ToTable("job_requirements", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.JobShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("ShiftCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shift_code");

                    b.HasKey("Id")
                        .HasName("pk_job_shifts");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_job_shifts_job_id");

                    b.ToTable("job_shifts", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.JobseekerAccommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccommodationCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accommodation_code");

                    b.Property<Guid>("JobseekerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobseeker_profile_id");

                    b.HasKey("Id")
                        .HasName("pk_jobseeker_accommodations");

                    b.HasIndex("JobseekerProfileId")
                        .HasDatabaseName("ix_jobseeker_accommodations_jobseeker_profile_id");

                    b.ToTable("jobseeker_accommodations", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.JobseekerExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("JobseekerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobseeker_profile_id");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("period");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_title");

                    b.HasKey("Id")
                        .HasName("pk_jobseeker_experiences");

                    b.HasIndex("JobseekerProfileId")
                        .HasDatabaseName("ix_jobseeker_experiences_jobseeker_profile_id");

                    b.ToTable("jobseeker_experiences", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.JobseekerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Availability")
                        .HasColumnType("text")
                        .HasColumnName("availability");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Conditions")
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<decimal>("MinHourlyPay")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("min_hourly_pay");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_jobseeker_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_jobseeker_profiles_user_id");

                    b.ToTable("jobseeker_profiles", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.JobseekerSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobseekerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobseeker_profile_id");

                    b.Property<string>("ScheduleCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schedule_code");

                    b.HasKey("Id")
                        .HasName("pk_jobseeker_schedules");

                    b.HasIndex("JobseekerProfileId")
                        .HasDatabaseName("ix_jobseeker_schedules_jobseeker_profile_id");

                    b.ToTable("jobseeker_schedules", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.JobseekerSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobseekerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobseeker_profile_id");

                    b.Property<string>("SkillCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_code");

                    b.HasKey("Id")
                        .HasName("pk_jobseeker_skills");

                    b.HasIndex("JobseekerProfileId")
                        .HasDatabaseName("ix_jobseeker_skills_jobseeker_profile_id");

                    b.ToTable("jobseeker_skills", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<bool>("IsSystemMessage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_message");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_messages_conversation_id");

                    b.HasIndex("SenderUserId")
                        .HasDatabaseName("ix_messages_sender_user_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.SavedJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("JobseekerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobseeker_profile_id");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at");

                    b.HasKey("Id")
                        .HasName("pk_saved_jobs");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_saved_jobs_job_id");

                    b.HasIndex("JobseekerProfileId", "JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_saved_jobs_jobseeker_profile_id_job_id");

                    b.ToTable("saved_jobs", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend_jobby.Models.Application", b =>
                {
                    b.HasOne("Backend_jobby.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_jobs_job_id");

                    b.HasOne("Backend_jobby.Models.JobseekerProfile", "JobseekerProfile")
                        .WithMany("Applications")
                        .HasForeignKey("JobseekerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_jobseeker_profiles_jobseeker_profile_id");

                    b.Navigation("Job");

                    b.Navigation("JobseekerProfile");
                });

            modelBuilder.Entity("Backend_jobby.Models.Conversation", b =>
                {
                    b.HasOne("Backend_jobby.Models.Application", "Application")
                        .WithOne("Conversation")
                        .HasForeignKey("Backend_jobby.Models.Conversation", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_applications_application_id");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Backend_jobby.Models.EmployerProfile", b =>
                {
                    b.HasOne("Backend_jobby.Models.User", "User")
                        .WithOne("EmployerProfile")
                        .HasForeignKey("Backend_jobby.Models.EmployerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employer_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend_jobby.Models.IgnoredJob", b =>
                {
                    b.HasOne("Backend_jobby.Models.Job", "Job")
                        .WithMany("IgnoredJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ignored_jobs_jobs_job_id");

                    b.HasOne("Backend_jobby.Models.JobseekerProfile", "JobseekerProfile")
                        .WithMany("IgnoredJobs")
                        .HasForeignKey("JobseekerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ignored_jobs_jobseeker_profiles_jobseeker_profile_id");

                    b.Navigation("Job");

                    b.Navigation("JobseekerProfile");
                });

            modelBuilder.Entity("Backend_jobby.Models.Job", b =>
                {
                    b.HasOne("Backend_jobby.Models.EmployerProfile", "EmployerProfile")
                        .WithMany("PostedJobs")
                        .HasForeignKey("EmployerProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_jobs_employer_profiles_employer_profile_id");

                    b.Navigation("EmployerProfile");
                });

            modelBuilder.Entity("Backend_jobby.Models.JobAccommodation", b =>
                {
                    b.HasOne("Backend_jobby.Models.Job", "Job")
                        .WithMany("Accommodations")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_accommodations_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Backend_jobby.Models.JobOffer", b =>
                {
                    b.HasOne("Backend_jobby.Models.Job", "Job")
                        .WithMany("Offers")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_offers_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Backend_jobby.Models.JobRequirement", b =>
                {
                    b.HasOne("Backend_jobby.Models.Job", "Job")
                        .WithMany("Requirements")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_requirements_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Backend_jobby.Models.JobShift", b =>
                {
                    b.HasOne("Backend_jobby.Models.Job", "Job")
                        .WithMany("Shifts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_shifts_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Backend_jobby.Models.JobseekerAccommodation", b =>
                {
                    b.HasOne("Backend_jobby.Models.JobseekerProfile", "JobseekerProfile")
                        .WithMany("Accommodations")
                        .HasForeignKey("JobseekerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jobseeker_accommodations_jobseeker_profiles_jobseeker_profi");

                    b.Navigation("JobseekerProfile");
                });

            modelBuilder.Entity("Backend_jobby.Models.JobseekerExperience", b =>
                {
                    b.HasOne("Backend_jobby.Models.JobseekerProfile", "JobseekerProfile")
                        .WithMany("Experiences")
                        .HasForeignKey("JobseekerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jobseeker_experiences_jobseeker_profiles_jobseeker_profile_");

                    b.Navigation("JobseekerProfile");
                });

            modelBuilder.Entity("Backend_jobby.Models.JobseekerProfile", b =>
                {
                    b.HasOne("Backend_jobby.Models.User", "User")
                        .WithOne("JobseekerProfile")
                        .HasForeignKey("Backend_jobby.Models.JobseekerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jobseeker_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend_jobby.Models.JobseekerSchedule", b =>
                {
                    b.HasOne("Backend_jobby.Models.JobseekerProfile", "JobseekerProfile")
                        .WithMany("Schedules")
                        .HasForeignKey("JobseekerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jobseeker_schedules_jobseeker_profiles_jobseeker_profile_id");

                    b.Navigation("JobseekerProfile");
                });

            modelBuilder.Entity("Backend_jobby.Models.JobseekerSkill", b =>
                {
                    b.HasOne("Backend_jobby.Models.JobseekerProfile", "JobseekerProfile")
                        .WithMany("Skills")
                        .HasForeignKey("JobseekerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jobseeker_skills_jobseeker_profiles_jobseeker_profile_id");

                    b.Navigation("JobseekerProfile");
                });

            modelBuilder.Entity("Backend_jobby.Models.Message", b =>
                {
                    b.HasOne("Backend_jobby.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");

                    b.HasOne("Backend_jobby.Models.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_sender_user_id");

                    b.Navigation("Conversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Backend_jobby.Models.SavedJob", b =>
                {
                    b.HasOne("Backend_jobby.Models.Job", "Job")
                        .WithMany("SavedJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_jobs_jobs_job_id");

                    b.HasOne("Backend_jobby.Models.JobseekerProfile", "JobseekerProfile")
                        .WithMany("SavedJobs")
                        .HasForeignKey("JobseekerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_jobs_jobseeker_profiles_jobseeker_profile_id");

                    b.Navigation("Job");

                    b.Navigation("JobseekerProfile");
                });

            modelBuilder.Entity("Backend_jobby.Models.Application", b =>
                {
                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Backend_jobby.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Backend_jobby.Models.EmployerProfile", b =>
                {
                    b.Navigation("PostedJobs");
                });

            modelBuilder.Entity("Backend_jobby.Models.Job", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("Applications");

                    b.Navigation("IgnoredJobs");

                    b.Navigation("Offers");

                    b.Navigation("Requirements");

                    b.Navigation("SavedJobs");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Backend_jobby.Models.JobseekerProfile", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("Applications");

                    b.Navigation("Experiences");

                    b.Navigation("IgnoredJobs");

                    b.Navigation("SavedJobs");

                    b.Navigation("Schedules");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Backend_jobby.Models.User", b =>
                {
                    b.Navigation("EmployerProfile");

                    b.Navigation("JobseekerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
