/* ------------------------------------------------------------------ */
/* Tööandja ja tema avatud kuulutused                                  */
/* ------------------------------------------------------------------ */
var EMPLOYER = {
  co:"CleanSpace Care", ini:"CS",
  et:{about:"Hooldusteenuste ettevõte, 40 töötajat. Objektid Tallinnas ja Harjumaal.",
      contact:"Pille Sarapuu · värbamisjuht · pille@cleanspace.näide.ee"},
  en:{about:"Facility services company, 40 employees. Sites in Tallinn and Harju county.",
      contact:"Pille Sarapuu · recruitment lead · pille@cleanspace.näide.ee"}
};

var POSTINGS = [
  {id:"p1", pay:7.00, place:"Ülemiste City", et:"Ärikliendi öökoristaja", en:"Commercial night cleaner"},
  {id:"p2", pay:9.50, place:"Harjumaa",      et:"Põrandahooldaja",        en:"Floor care technician"},
  {id:"p3", pay:7.60, place:"Kristiine",     et:"Trepikodade koristaja",  en:"Stairwell cleaner"}
];

/* ------------------------------------------------------------------ */
/* Kandidaadid — tööotsijad, kes on paremale swipe'inud ja CV saatnud  */
/* ------------------------------------------------------------------ */
var CANDIDATES = [
  {id:1, name:"Kadri Lepik", ini:"KL", posting:"p1", km:2.5, at:"eile 18:20", tailored:true,
   accom:["max10","stepfree","lownoise"],
   et:{wants:"Õhtune vahetus, osaline koormus",
       summary:"Kogenud koristaja, kes otsib õhtust osalise koormusega tööd. Töötan hoolikalt ja iseseisvalt, olen harjunud kindla kontrollnimekirja järgi töötama.",
       exp:[{role:"Koristaja", org:"Büroohaldus OÜ", period:"2023–2026",
             text:"Kolme kontorihoone õhtune koristus, 4 tundi vahetuses. Vastutasin oma objektide varude tellimise eest."},
            {role:"Abitööline", org:"Hansa Pesumaja", period:"2021–2023",
             text:"Voodipesu sorteerimine ja pakkimine, tööstuslike masinate laadimine."}],
       skills:["Ärikliendi koristus","Põrandate poleerimine","Puhastusainete ohutu käsitsemine","Eesti ja vene keel"],
       availability:"E, K, R õhtuti alates 17:00. Saab alustada kahe nädala jooksul.",
       conditions:"Tõstab kuni 10 kg. Vajab astmeteta ligipääsu. Eelistab madalat müra.",
       first:"Tere! Suur tänu kutse eest. Ülemiste objekt sobib mulle hästi, olen seal kandis varem töötanud."},
   en:{wants:"Evening shift, part-time",
       summary:"Experienced cleaner looking for part-time evening work. I work carefully and independently, and I'm used to following a fixed checklist.",
       exp:[{role:"Cleaner", org:"Büroohaldus OÜ", period:"2023–2026",
             text:"Evening cleaning of three office buildings, 4-hour shifts. Responsible for ordering supplies for my own sites."},
            {role:"Assistant", org:"Hansa Pesumaja", period:"2021–2023",
             text:"Sorting and packing linen, loading industrial machines."}],
       skills:["Commercial cleaning","Floor buffing","Safe handling of cleaning agents","Estonian and Russian"],
       availability:"Mon, Wed, Fri evenings from 17:00. Can start within two weeks.",
       conditions:"Lifts up to 10 kg. Needs step-free access. Prefers a low-noise environment.",
       first:"Hello! Thank you for getting in touch. The Ülemiste site suits me well, I've worked in that area before."}},

  {id:2, name:"Marek Tooming", ini:"MT", posting:"p1", km:4.8, at:"eile 21:05", tailored:false,
   accom:["max10","stepfree"],
   et:{wants:"Õhtune või öine vahetus, täiskoormus",
       summary:"Otsin kindlat õhtust tööd. Olen täpne ja ei jäta tööd pooleli.",
       exp:[{role:"Koristaja", org:"Keskuse Kaubamaja", period:"2024–2026",
             text:"Kaubanduskeskuse üldalade koristus õhtuti pärast sulgemist."},
            {role:"Laotööline", org:"Logistika Depoo AS", period:"2019–2024",
             text:"Kaupade vastuvõtt ja paigutamine, kahveltõstuki luba."}],
       skills:["Ärikliendi koristus","Kahveltõstuki luba","Eesti keel"],
       availability:"Kõik õhtud, saab alustada kohe.",
       conditions:"Tõstab kuni 10 kg. Vajab astmeteta ligipääsu.",
       first:"Tere! Olen valmis kohe alustama, ka juba sel nädalal."},
   en:{wants:"Evening or night shift, full-time",
       summary:"Looking for steady evening work. I'm precise and I don't leave things half-done.",
       exp:[{role:"Cleaner", org:"Keskuse Kaubamaja", period:"2024–2026",
             text:"Cleaning the shopping centre's common areas after closing."},
            {role:"Warehouse worker", org:"Logistika Depoo AS", period:"2019–2024",
             text:"Goods receipt and put-away, forklift licence."}],
       skills:["Commercial cleaning","Forklift licence","Estonian"],
       availability:"Every evening, can start immediately.",
       conditions:"Lifts up to 10 kg. Needs step-free access.",
       first:"Hello! I'm ready to start right away, even this week."}},

  {id:3, name:"Olga Ivanova", ini:"OI", posting:"p1", km:1.9, at:"täna 09:12", tailored:true,
   accom:["max10","stepfree","lownoise","sitting"],
   et:{wants:"Õhtune vahetus, 3 korda nädalas",
       summary:"Kaheksa aastat koristustööd büroohoonetes. Ülemiste kvartal on mulle tuttav, olen seal kahes majas töötanud.",
       exp:[{role:"Vanemkoristaja", org:"Puhas Maja OÜ", period:"2020–2026",
             text:"Neli objekti, uute töötajate väljaõpe, varude arvestus."},
            {role:"Koristaja", org:"Hotell Marina", period:"2017–2020",
             text:"Hotellitubade ettevalmistus, 12 tuba vahetuses."}],
       skills:["Ärikliendi koristus","Uute töötajate juhendamine","Eesti ja vene keel","Põrandate poleerimine"],
       availability:"T, N, R õhtuti. Saab alustada kuu lõpust.",
       conditions:"Tõstab kuni 10 kg. Vajab astmeteta ligipääsu ja istumispause.",
       first:"Tere! Olen Ülemiste kvartalis varem töötanud, tean seal maju hästi."},
   en:{wants:"Evening shift, 3 days a week",
       summary:"Eight years of cleaning in office buildings. I know the Ülemiste quarter — I've worked in two buildings there.",
       exp:[{role:"Senior cleaner", org:"Puhas Maja OÜ", period:"2020–2026",
             text:"Four sites, training new staff, stock control."},
            {role:"Cleaner", org:"Hotell Marina", period:"2017–2020",
             text:"Preparing hotel rooms, 12 rooms per shift."}],
       skills:["Commercial cleaning","Training new staff","Estonian and Russian","Floor buffing"],
       availability:"Tue, Thu, Fri evenings. Can start at the end of the month.",
       conditions:"Lifts up to 10 kg. Needs step-free access and seated breaks.",
       first:"Hello! I've worked in the Ülemiste quarter before, I know the buildings well."}},

  {id:4, name:"Taavi Rand", ini:"TR", posting:"p2", km:7.2, at:"eile 14:40", tailored:true,
   accom:["mask","stepfree","max10"],
   et:{wants:"Öine vahetus, täiskoormus",
       summary:"Põrandamasinate kogemus viis aastat: pesumasin, poleerija, vahatamine. Olen töötanud nii tootmis- kui kaubanduspindadel.",
       exp:[{role:"Põrandahooldaja", org:"Polaris Hoolduskeskus", period:"2021–2026",
             text:"Suurte pindade põrandahooldus öisel ajal, masinate hooldus ja väikeremont."},
            {role:"Koristaja", org:"Toidutehas Verde", period:"2019–2021",
             text:"Tootmisruumide puhastus, toiduohutuse nõuete järgimine."}],
       skills:["Põrandate poleerimine","Masinate hooldus","Toiduohutus","Eesti keel"],
       availability:"E–N öösiti. Etteteatamisaeg kaks nädalat.",
       conditions:"Kasutab tolmumaski. Vajab astmeteta ligipääsu.",
       first:"Tere! Masinad on mulle tuttavad, väljaõpet eraldi vaja ei ole."},
   en:{wants:"Night shift, full-time",
       summary:"Five years with floor machines: scrubber, polisher, waxing. I've worked both production and retail floors.",
       exp:[{role:"Floor care technician", org:"Polaris Hoolduskeskus", period:"2021–2026",
             text:"Night-time floor care on large surfaces, machine servicing and minor repairs."},
            {role:"Cleaner", org:"Toidutehas Verde", period:"2019–2021",
             text:"Cleaning production rooms, following food safety requirements."}],
       skills:["Floor buffing","Machine maintenance","Food safety","Estonian"],
       availability:"Mon–Thu nights. Two weeks' notice.",
       conditions:"Uses a dust mask. Needs step-free access.",
       first:"Hello! I know the machines, no separate training needed."}},

  {id:5, name:"Jana Mets", ini:"JM", posting:"p3", km:3.1, at:"täna 11:30", tailored:false,
   accom:["stepfree","max10","sitting"],
   et:{wants:"Oma tempos töö, 2 korda nädalas",
       summary:"Otsin tööd, mille tempo on minu enda määrata. Trepikodade hooldus sobib selleks hästi.",
       exp:[{role:"Koristaja", org:"Sõle Spordikeskus", period:"2022–2026",
             text:"Riietusruumide ja saalide koristus õhtuti pärast treeninguid."}],
       skills:["Ärikliendi koristus","Lõhnavabade vahendite kasutamine","Eesti keel"],
       availability:"Kokkuleppel, eelistan päevaseid tunde. Saab alustada kohe.",
       conditions:"Tõstab kuni 10 kg. Vajab astmeteta ligipääsu ja istumispause.",
       first:"Tere! Kristiine on mulle käe-jala juures, jõuan kõndides."},
   en:{wants:"Work at my own pace, twice a week",
       summary:"Looking for work where I set the pace. Stairwell maintenance suits that well.",
       exp:[{role:"Cleaner", org:"Sõle Spordikeskus", period:"2022–2026",
             text:"Cleaning changing rooms and halls in the evening after training sessions."}],
       skills:["Commercial cleaning","Working with fragrance-free products","Estonian"],
       availability:"By agreement, prefer daytime hours. Can start immediately.",
       conditions:"Lifts up to 10 kg. Needs step-free access and seated breaks.",
       first:"Hello! Kristiine is right next to me, I can walk there."}},

  {id:6, name:"Priit Kaljula", ini:"PK", posting:"p1", km:9.6, at:"2 p tagasi", tailored:false,
   accom:["stepfree"],
   et:{wants:"Õhtune vahetus, osaline koormus",
       summary:"Vahetan ametit ja otsin õhtust lisatööd. Varasem koristuskogemus puudub, aga õpin kiiresti.",
       exp:[{role:"Klienditeenindaja", org:"Keskuse Kaubamaja", period:"2022–2026",
             text:"Kassatöö ja riiulite täitmine, vahetustega graafik."}],
       skills:["Klienditeenindus","Eesti ja inglise keel"],
       availability:"E–R õhtuti. Saab alustada kuu pärast.",
       conditions:"Vajab astmeteta ligipääsu.",
       first:"Tere! Kogemust mul koristuses pole, aga olen valmis õppima."},
   en:{wants:"Evening shift, part-time",
       summary:"Changing careers and looking for evening work. No prior cleaning experience, but I learn fast.",
       exp:[{role:"Sales assistant", org:"Keskuse Kaubamaja", period:"2022–2026",
             text:"Till work and restocking shelves, shift rota."}],
       skills:["Customer service","Estonian and English"],
       availability:"Mon–Fri evenings. Can start in a month.",
       conditions:"Needs step-free access.",
       first:"Hello! I have no cleaning experience, but I'm ready to learn."}},

  {id:7, name:"Svetlana Kuznetsova", ini:"SK", posting:"p3", km:2.4, at:"täna 08:05", tailored:true,
   accom:["stepfree","max10","sitting","nochem"],
   et:{wants:"Hommikused või päevased tunnid",
       summary:"Kaksteist aastat kortermajade hooldust. Tean, mis trepikojas tegelikult aega võtab ja mida elanikud märkavad.",
       exp:[{role:"Majahoidja", org:"Puhas Maja OÜ", period:"2014–2026",
             text:"Kuue kortermaja trepikojad ja õuealad, suhtlus korteriühistutega."}],
       skills:["Trepikodade hooldus","Lõhnavabad vahendid","Eesti ja vene keel","Suhtlus ühistutega"],
       availability:"E–R päeval. Etteteatamisaeg üks kuu.",
       conditions:"Tõstab kuni 10 kg. Vajab astmeteta ligipääsu, ei kasuta tugevaid kemikaale.",
       first:"Tere! Kristiine majad on mulle tuttavad, olen seal kandis aastaid töötanud."},
   en:{wants:"Morning or daytime hours",
       summary:"Twelve years maintaining apartment buildings. I know what actually takes time in a stairwell and what residents notice.",
       exp:[{role:"Caretaker", org:"Puhas Maja OÜ", period:"2014–2026",
             text:"Stairwells and grounds of six apartment buildings, liaison with housing associations."}],
       skills:["Stairwell maintenance","Fragrance-free products","Estonian and Russian","Working with housing associations"],
       availability:"Mon–Fri daytime. One month's notice.",
       conditions:"Lifts up to 10 kg. Needs step-free access, does not use harsh chemicals.",
       first:"Hello! I know the Kristiine buildings, I've worked in that area for years."}},

  {id:8, name:"Rasmus Vaher", ini:"RV", posting:"p2", km:12.8, at:"3 p tagasi", tailored:false,
   accom:["mask","stepfree","max10","lownoise"],
   et:{wants:"Öine vahetus, osaline koormus",
       summary:"Olen põrandamasinaga töötanud kaks hooaega suvetöödel. Soovin selle kõrvalt täiendavat väljaõpet.",
       exp:[{role:"Hooajatööline", org:"Põrandapesu Grupp", period:"2024–2025",
             text:"Büroohoonete põrandate pesu ja poleerimine õhtusel ajal, juhendaja käe all."}],
       skills:["Põrandate poleerimine","Eesti keel"],
       availability:"T ja N öösiti, hiljem rohkem. Saab alustada kahe nädala pärast.",
       conditions:"Kasutab tolmumaski ja kõrvaklappe. Vajab astmeteta ligipääsu.",
       first:"Tere! Olen masinaga töötanud, aga täiendav väljaõpe kuluks ära."},
   en:{wants:"Night shift, part-time",
       summary:"I've worked with a floor machine for two summer seasons. I'd like further training alongside the job.",
       exp:[{role:"Seasonal worker", org:"Põrandapesu Grupp", period:"2024–2025",
             text:"Washing and polishing office floors in the evening, under supervision."}],
       skills:["Floor buffing","Estonian"],
       availability:"Tue and Thu nights, more later. Can start in two weeks.",
       conditions:"Uses a dust mask and ear defenders. Needs step-free access.",
       first:"Hello! I've used the machine, but extra training would help."}}
];
